import Head from "next/head";
import Header from "../components/Header";
import NavBar from "../components/NavBar";
import Results from "../components/Results";
import request from "../utils/request";

export async function getServerSideProps(context) {
  const url = "https://api.themoviedb.org/3";
  const genre = context.query.genre;
  // console.log({ genre });

  const response = await fetch(
    `${url}${request[genre]?.url || request.fetchTrending.url}`
  )
    .then((data) => data.json())
    .then((data) => {
      const response = data.results;
      return response;
    });
  
  return {
    props: { response }, // will be passed to the page component as props
  };
}

export default function Home({ response }) {
  // console.log(response);
  return (
    <div>
      <Head>
        <title>Hull-ux</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <NavBar />
      <Results response={response} />
    </div>
  );
}
